from scrapers.venues import (
    annexet,
    aviciiarena,
    bagarmossen,
    berns,
    berwaldhallen,
    bioaspen,
    cirkus,
    debaser,
    encore,
    engelen,
    ericericsonhallen,
    fallan,
    fasching,
    fryshuset,
    fylkingen,
    glennmillercafe,
    gotalejon,
    gronalund,
    hartwig,
    hovet,
    hus7,
    kmh,
    kollektivetlivet,
    konserthuset,
    kulturhuset,
    kungcarls,
    landet,
    larryscorner,
    nalen,
    petsoundsbar,
    reimersholme,
    riche,
    ronnells,
    scalateatern,
    slaktkyrkan,
    sodrateatern,
    stampen,
    strawberryarena,
    trearena,
)

SOURCES = (
    ("debaser", debaser.fetch),
    ("nalen", nalen.fetch),
    ("fallan", fallan.fetch),
    ("slaktkyrkan", slaktkyrkan.fetch),
    ("hus7", hus7.fetch),
    ("kollektivetlivet", kollektivetlivet.fetch),
    ("sodrateatern", sodrateatern.fetch),
    ("berns", berns.fetch),
    ("cirkus", cirkus.fetch),
    ("fryshuset", fryshuset.fetch),
    ("kulturhuset", kulturhuset.fetch),
    ("hartwig", hartwig.fetch),
    ("annexet", annexet.fetch),
    ("hovet", hovet.fetch),
    ("aviciiarena", aviciiarena.fetch),
    ("trearena", trearena.fetch),
    ("strawberryarena", strawberryarena.fetch),
    ("konserthuset", konserthuset.fetch),
    ("berwaldhallen", berwaldhallen.fetch),
    ("fasching", fasching.fetch),
    ("stampen", stampen.fetch),
    ("glennmillercafe", glennmillercafe.fetch),
    ("kungcarls", kungcarls.fetch),
    ("engelen", engelen.fetch),
    ("petsoundsbar", petsoundsbar.fetch),
    ("reimersholme", reimersholme.fetch),
    ("riche", riche.fetch),
    ("landet", landet.fetch),
    ("encore", encore.fetch),
    ("bioaspen", bioaspen.fetch),
    ("scalateatern", scalateatern.fetch),
    ("gotalejon", gotalejon.fetch),
    ("bagarmossen", bagarmossen.fetch),
    ("kmh", kmh.fetch),
    ("ericericsonhallen", ericericsonhallen.fetch),
    ("gronalund", gronalund.fetch),
    ("fylkingen", fylkingen.fetch),
    ("ronnells", ronnells.fetch),
    ("larryscorner", larryscorner.fetch),
)
